### ISSUE TITLE
Docker for Windows - Failed to set permissions of file

### ISSUE THREAD

**Issue by jarzebowsky** [mickaelperrin/docker-magic-sync#8] opened 2018-10-15 17:40 UTC
`Failed to set permissions of file /usr/share/nginx/html/test.magic/js-translation.json to ?????w??w?: the permissions was set to ?????-??-? instead. The filesystem probably does not support all permission bits. If this is a FAT filesystem, you should set the "fat" option to true. Otherwise, you should probably set the "perms" option to 0o1755 (or to 0 if you don't need to synchronize permissions).`

There is such a wall of this error message for every file. Will `perms=0` will resolve this issue? If so where I'm supposed to enter it?

**Comment by mickaelperrin** [comment] 2018-10-16 09:45
What's your base OS ? Windows ?

**Comment by jarzebowsky** [comment] 2018-10-16 10:35
@mickaelperrin As title says Docker for Windows.
Yes, Windows 10 Enterprise Version 1709 

Docker-sync have something like `sync_args` where you can add `['perms' = 0]` which should fix problem there, but docker-sync is not friendly for Windows anymore so I came here to get it working and have problem when getting error above. Probably that `perms=0` flag would resolve the issue, but don't know how I can provide it to unison.

**Comment by mickaelperrin** [comment] 2018-10-16 10:42
Ah, sorry, didn't see it ;)

I never tested it on windows, only on MacOS. It looks like the issue is related to unison struggling with permissions.

Try passing a new env variable: 
```
SYNC_UNISON_DEFAULTS="-perms=0 -auto -numericids -batch -maxerrors 10 -repeat watch"
```

**Comment by jarzebowsky** [comment] 2018-10-16 11:11
Seems it's working need to test it more. 

Other topic is can you implement script which will run watch bindings for changes on windows?
Like this: http://blog.subjectify.us/miscellaneous/2017/04/24/docker-for-windows-watch-bindings.html?

Without it Windows version is unusable.

**Comment by mickaelperrin** [comment] 2018-10-16 11:20
Thanks for your feedback.

I will close this issue feel free to reopen it if you have related troubles.

For your other request, please open a new issue and exposes the problem issued. As said, I work only on MacOS and I won't work on Windows related issues, but other might want. Feel free to submit a pull request I will have a look and test it on MacOS before merging.

**Closed as completed by mickaelperrin** 2018-10-16 11:20 UTC
